### ISSUE TITLE
Transfering WNAM to namada should burn the same amount

### ISSUE THREAD

**Issue by Fraccaman** [anoma/ethereum-bridge#58]

**Comment by sug0** [comment]
For this issue and #56, could we do something like the gravity bridge does,

https://github.com/Gravity-Bridge/Gravity-Bridge/blob/8ba6deb81373d9d3b702d22d20bca028f74dc2ed/solidity/contracts/Gravity.sol#L590-L609

https://github.com/Gravity-Bridge/Gravity-Bridge/blob/8ba6deb81373d9d3b702d22d20bca028f74dc2ed/solidity/contracts/CosmosToken.sol#L33

where one contract owns the maximum representable supply of the native token?

In our case, the `Vault` could mint `MAX_UINT` worth of `wNAM`. On transfers to Ethereum, if the vault detected the transferred asset was `wNAM`, it would release `wNAM` from its internal pool, since it owns the entire representable supply. Transferring to Namada, we could "burn" tokens by transferring them back to the `Vault`.
